spring:
  datasource:
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://localhost:15432/postgres?currentSchema=campus_card
    username: gaussdb
    password: OpenGauss@123

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB       # 单个文件最大 10MB
      max-request-size: 20MB    # 整个请求最大 20MB
      
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080

